import { useEffect, useState } from 'react'
import Sidebar from '../../components/Sidebar.jsx'
import StatusBadge from '../../components/StatusBadge.jsx'
import API from '../../api/axios.js'
import Loader from '../../components/Loader.jsx'
import { FiSearch, FiEdit2, FiDownload, FiRefreshCw, FiTrash2 } from 'react-icons/fi'
import { PieChart, Pie, Cell, BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'

const SuperPanel = () => {
  const [tickets, setTickets] = useState([])
  const [users, setUsers] = useState([])
  const [stats, setStats] = useState(null)
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [statusFilter, setStatusFilter] = useState('')
  const [editingId, setEditingId] = useState(null)
  const [newStatus, setNewStatus] = useState('')
  const [activeTab, setActiveTab] = useState('tickets')

  const fetchData = async () => {
    try {
      setLoading(true)
      
      const dashRes = await API.get('/dashboard/admin')
      setStats(dashRes.data.stats)

      const ticketsRes = await API.get('/tickets', { 
        params: { 
          limit: 200,
          ...(search && { search }),
          ...(statusFilter && { status: statusFilter })
        } 
      })
      setTickets(ticketsRes.data.tickets || [])

      const usersRes = await API.get('/users')
      setUsers(usersRes.data.users || [])
    } catch (error) {
      console.log(error)
      alert('❌ Error loading data')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchData()
  }, [search, statusFilter])

  // UPDATE - Status Change
  const handleStatusChange = async (ticketId) => {
    if (!newStatus) {
      alert('❌ Please select a status')
      return
    }
    try {
      console.log('Updating ticket:', ticketId, 'Status:', newStatus)
      await API.put(`/tickets/${ticketId}`, { status: newStatus })
      
      setTickets(tickets.map(t => 
        t.id === ticketId ? { ...t, status: newStatus } : t
      ))
      
      setEditingId(null)
      setNewStatus('')
      alert('✅ Status updated successfully!')
      fetchData() // Refresh data
    } catch (error) {
      console.error('Error:', error)
      alert('❌ Error updating status: ' + error.message)
    }
  }

  // DELETE - Remove Ticket
  const handleDeleteTicket = async (ticketId) => {
    if (window.confirm('⚠️ کیا آپ یہ ticket permanently delete کرنا چاہتے ہیں؟')) {
      try {
        await API.delete(`/tickets/${ticketId}`)
        setTickets(tickets.filter(t => t.id !== ticketId))
        alert('✅ Ticket deleted successfully!')
      } catch (error) {
        alert('❌ Error deleting ticket: ' + error.message)
      }
    }
  }

  const downloadReport = () => {
    const report = `
╔════════════════════════════════════════════════════════════╗
║     SUPPORT DESK - SYSTEM REPORT                          ║
║     Group 11: Jawad Ahmed & Ghulam Husnain               ║
╚════════════════════════════════════════════════════════════╝

📅 Generated: ${new Date().toLocaleDateString('en-PK')} ${new Date().toLocaleTimeString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📊 TICKET STATISTICS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total Tickets:           ${stats?.totalTickets || 0}
🔴 Pending (Open):       ${stats?.openTickets || 0}
🟡 In Progress:          ${stats?.inProgressTickets || 0}
✅ Resolved:             ${stats?.resolvedTickets || 0}

📈 Completion Rate:      ${stats?.totalTickets ? Math.round((stats.resolvedTickets / stats.totalTickets) * 100) : 0}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
👥 USER INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total Users:             ${users.length}
🔴 Admins:               ${users.filter(u => u.role === 'admin').length}
🔵 Agents:               ${users.filter(u => u.role === 'agent').length}
🟢 Regular Users:        ${users.filter(u => u.role === 'user').length}
✅ Active Users:         ${users.filter(u => u.is_active).length}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📋 TOP 15 TICKETS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${tickets.slice(0, 15).map((t, i) => `${i+1}. [${t.status.toUpperCase()}] ${t.title} (ID: ${t.id})`).join('\n')}

═══════════════════════════════════════════════════════════════
Report Generated by Support Desk System
Complaint & Support Ticket Management System v1.0
    `.trim()

    const element = document.createElement('a')
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(report))
    element.setAttribute('download', `support-report-${new Date().getTime()}.txt`)
    element.style.display = 'none'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  if (loading) return <Loader />

  const statusChartData = [
    { name: '🔴 Pending', value: stats?.openTickets || 0, fill: '#EF4444' },
    { name: '🟡 Progress', value: stats?.inProgressTickets || 0, fill: '#F59E0B' },
    { name: '✅ Resolved', value: stats?.resolvedTickets || 0, fill: '#10B981' }
  ]

  const userRoleData = [
    { name: 'Admin', value: users.filter(u => u.role === 'admin').length, fill: '#DC2626' },
    { name: 'Agent', value: users.filter(u => u.role === 'agent').length, fill: '#3B82F6' },
    { name: 'User', value: users.filter(u => u.role === 'user').length, fill: '#10B981' }
  ]

  const weeklyData = [
    { day: 'Mon', open: 5, resolved: 2, progress: 3 },
    { day: 'Tue', open: 4, resolved: 3, progress: 2 },
    { day: 'Wed', open: 6, resolved: 4, progress: 2 },
    { day: 'Thu', open: 7, resolved: 5, progress: 2 },
    { day: 'Fri', open: 8, resolved: 6, progress: 2 },
    { day: 'Sat', open: 3, resolved: 2, progress: 1 },
    { day: 'Sun', open: 2, resolved: 1, progress: 1 }
  ]

  return (
    <div className='flex min-h-screen bg-gray-50'>
      <Sidebar />
      <div className='flex-1 flex flex-col'>
        {/* Header */}
        <div className='bg-gradient-to-r from-green-600 via-emerald-600 to-teal-600 text-white px-8 py-8 sticky top-0 z-10 shadow-2xl'>
          <div className='flex justify-between items-center'>
            <div className='animate-in slide-in-from-left duration-700'>
              <h1 className='text-4xl font-bold'>🎛️ Super Admin Panel</h1>
              <p className='text-green-100 text-sm mt-1'>Complete System Management & Reporting</p>
            </div>
            <div className='flex gap-3 animate-in slide-in-from-right duration-700'>
              <button
                onClick={fetchData}
                className='flex items-center gap-2 bg-white/20 text-white px-4 py-2 rounded-lg hover:bg-white/30 transition-all duration-300 font-bold'
              >
                <FiRefreshCw /> Refresh
              </button>
              <button
                onClick={downloadReport}
                className='flex items-center gap-2 bg-white text-green-600 px-4 py-2 rounded-lg hover:bg-gray-100 hover:shadow-lg transform hover:scale-105 transition-all duration-300 font-bold'
              >
                <FiDownload /> Report
              </button>
            </div>
          </div>
        </div>

        <div className='flex-1 p-8 overflow-y-auto'>
          {/* Quick Stats */}
          <div className='grid grid-cols-5 gap-4 mb-8 animate-in fade-in duration-700'>
            <div className='bg-gradient-to-br from-green-50 to-emerald-50 rounded-xl border-2 border-green-200 p-6 shadow-lg hover:shadow-xl transition-all text-center transform hover:scale-105 duration-300'>
              <p className='text-green-700 text-sm font-bold'>Total Tickets</p>
              <p className='text-4xl font-bold text-green-600 mt-3'>{stats?.totalTickets || 0}</p>
            </div>
            <div className='bg-gradient-to-br from-red-50 to-red-100 rounded-xl border-2 border-red-200 p-6 shadow-lg hover:shadow-xl transition-all text-center transform hover:scale-105 duration-300'>
              <p className='text-red-700 text-sm font-bold'>🔴 Pending</p>
              <p className='text-4xl font-bold text-red-600 mt-3'>{stats?.openTickets || 0}</p>
            </div>
            <div className='bg-gradient-to-br from-yellow-50 to-yellow-100 rounded-xl border-2 border-yellow-200 p-6 shadow-lg hover:shadow-xl transition-all text-center transform hover:scale-105 duration-300'>
              <p className='text-yellow-700 text-sm font-bold'>🟡 Progress</p>
              <p className='text-4xl font-bold text-yellow-600 mt-3'>{stats?.inProgressTickets || 0}</p>
            </div>
            <div className='bg-gradient-to-br from-emerald-50 to-green-100 rounded-xl border-2 border-emerald-200 p-6 shadow-lg hover:shadow-xl transition-all text-center transform hover:scale-105 duration-300'>
              <p className='text-emerald-700 text-sm font-bold'>✅ Resolved</p>
              <p className='text-4xl font-bold text-emerald-600 mt-3'>{stats?.resolvedTickets || 0}</p>
            </div>
            <div className='bg-gradient-to-br from-blue-50 to-blue-100 rounded-xl border-2 border-blue-200 p-6 shadow-lg hover:shadow-xl transition-all text-center transform hover:scale-105 duration-300'>
              <p className='text-blue-700 text-sm font-bold'>👥 Users</p>
              <p className='text-4xl font-bold text-blue-600 mt-3'>{users.length}</p>
            </div>
          </div>

          {/* Charts Section */}
          <div className='grid grid-cols-3 gap-6 mb-8'>
            <div className='bg-white rounded-xl border-2 border-gray-200 p-6 shadow-lg'>
              <h3 className='text-lg font-bold text-gray-800 mb-4'>📊 Ticket Status</h3>
              <ResponsiveContainer width='100%' height={250}>
                <PieChart>
                  <Pie
                    data={statusChartData}
                    cx='50%'
                    cy='50%'
                    labelLine={false}
                    label={({ name, value }) => `${name}: ${value}`}
                    outerRadius={80}
                    fill='#8884d8'
                    dataKey='value'
                  >
                    {statusChartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.fill} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            </div>

            <div className='bg-white rounded-xl border-2 border-gray-200 p-6 shadow-lg'>
              <h3 className='text-lg font-bold text-gray-800 mb-4'>👥 User Roles</h3>
              <ResponsiveContainer width='100%' height={250}>
                <BarChart data={userRoleData}>
                  <CartesianGrid strokeDasharray='3 3' />
                  <XAxis dataKey='name' />
                  <YAxis />
                  <Tooltip />
                  <Bar dataKey='value' fill='#3B82F6' radius={[8, 8, 0, 0]}>
                    {userRoleData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.fill} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>

            <div className='bg-white rounded-xl border-2 border-gray-200 p-6 shadow-lg'>
              <h3 className='text-lg font-bold text-gray-800 mb-4'>📈 Weekly Trend</h3>
              <ResponsiveContainer width='100%' height={250}>
                <LineChart data={weeklyData}>
                  <CartesianGrid strokeDasharray='3 3' />
                  <XAxis dataKey='day' />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Line type='monotone' dataKey='open' stroke='#EF4444' strokeWidth={2} />
                  <Line type='monotone' dataKey='progress' stroke='#F59E0B' strokeWidth={2} />
                  <Line type='monotone' dataKey='resolved' stroke='#10B981' strokeWidth={2} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Tabs */}
          <div className='flex gap-2 mb-6 bg-white rounded-lg border-2 border-gray-200 p-1 shadow-lg'>
            <button
              onClick={() => setActiveTab('tickets')}
              className={`flex-1 px-4 py-3 rounded text-sm font-bold transition-all ${
                activeTab === 'tickets'
                  ? 'bg-gradient-to-r from-green-600 to-emerald-600 text-white'
                  : 'text-gray-600 hover:text-gray-900'
              }`}
            >
              📋 All Tickets ({tickets.length})
            </button>
            <button
              onClick={() => setActiveTab('users')}
              className={`flex-1 px-4 py-3 rounded text-sm font-bold transition-all ${
                activeTab === 'users'
                  ? 'bg-gradient-to-r from-green-600 to-emerald-600 text-white'
                  : 'text-gray-600 hover:text-gray-900'
              }`}
            >
              👥 Users ({users.length})
            </button>
          </div>

          {/* TICKETS TAB */}
          {activeTab === 'tickets' && (
            <div className='space-y-4'>
              <div className='bg-white rounded-lg border-2 border-gray-200 p-4 shadow-lg'>
                <div className='grid grid-cols-3 gap-4'>
                  <div className='relative'>
                    <FiSearch className='absolute left-3 top-1/2 -translate-y-1/2 text-gray-400' />
                    <input
                      type='text'
                      value={search}
                      onChange={(e) => setSearch(e.target.value)}
                      placeholder='Search tickets...'
                      className='w-full border-2 border-gray-300 rounded px-10 py-2 text-sm focus:outline-none focus:border-green-500 focus:ring-2 focus:ring-green-200 font-semibold text-gray-800'
                    />
                  </div>
                  <select
                    value={statusFilter}
                    onChange={(e) => setStatusFilter(e.target.value)}
                    className='border-2 border-gray-300 rounded px-4 py-2 text-sm focus:outline-none focus:border-green-500 focus:ring-2 focus:ring-green-200 bg-white font-semibold text-gray-700'
                  >
                    <option value=''>All Status</option>
                    <option value='open'>🔴 Pending</option>
                    <option value='in_progress'>🟡 In Progress</option>
                    <option value='resolved'>✅ Resolved</option>
                  </select>
                  <button
                    onClick={fetchData}
                    className='bg-gradient-to-r from-green-600 to-emerald-600 text-white px-4 py-2 rounded text-sm font-bold hover:shadow-lg'
                  >
                    🔄 Refresh
                  </button>
                </div>
              </div>

              <div className='bg-white rounded-lg border-2 border-gray-200 overflow-hidden shadow-lg'>
                {tickets.length === 0 ? (
                  <div className='p-12 text-center text-gray-400'>
                    <p className='text-lg font-semibold'>No tickets found</p>
                  </div>
                ) : (
                  <div className='overflow-x-auto'>
                    <table className='w-full text-sm'>
                      <thead>
                        <tr className='bg-gradient-to-r from-gray-100 to-gray-50 border-b-2 border-gray-300'>
                          <th className='px-6 py-4 text-left font-bold text-gray-800'>ID</th>
                          <th className='px-6 py-4 text-left font-bold text-gray-800'>Title</th>
                          <th className='px-6 py-4 text-left font-bold text-gray-800'>User</th>
                          <th className='px-6 py-4 text-left font-bold text-gray-800'>Priority</th>
                          <th className='px-6 py-4 text-left font-bold text-gray-800'>Current Status</th>
                          <th className='px-6 py-4 text-left font-bold text-gray-800'>Change To</th>
                          <th className='px-6 py-4 text-left font-bold text-gray-800'>Action</th>
                          <th className='px-6 py-4 text-left font-bold text-gray-800'>Date</th>
                        </tr>
                      </thead>
                      <tbody className='divide-y'>
                        {tickets.map((t) => (
                          <tr key={t.id} className='hover:bg-green-50 transition-colors'>
                            <td className='px-6 py-4 font-bold text-green-600'>#{t.id}</td>
                            <td className='px-6 py-4 font-medium text-gray-800'>{t.title}</td>
                            <td className='px-6 py-4'>
                              <div className='text-sm'>
                                <p className='font-bold text-gray-800'>{t.creator?.name}</p>
                                <p className='text-xs text-gray-500'>{t.creator?.email}</p>
                              </div>
                            </td>
                            <td className='px-6 py-4'>
                              <StatusBadge priority={t.priority} />
                            </td>
                            <td className='px-6 py-4'>
                              <StatusBadge status={t.status} />
                            </td>
                            <td className='px-6 py-4'>
                              {editingId === t.id ? (
                                <select
                                  value={newStatus}
                                  onChange={(e) => setNewStatus(e.target.value)}
                                  className='border-2 border-green-500 rounded px-2 py-1 text-xs bg-white focus:outline-none font-bold text-gray-800'
                                >
                                  <option value=''>Select Status</option>
                                  <option value='open'>🔴 Pending</option>
                                  <option value='in_progress'>🟡 In Progress</option>
                                  <option value='resolved'>✅ Resolved</option>
                                  <option value='closed'>⚫ Closed</option>
                                </select>
                              ) : (
                                <span className='text-gray-500 text-xs font-bold'>-</span>
                              )}
                            </td>
                            <td className='px-6 py-4'>
                              {editingId === t.id ? (
                                <div className='flex gap-2'>
                                  <button
                                    onClick={() => handleStatusChange(t.id)}
                                    className='bg-green-600 text-white text-xs px-3 py-1 rounded hover:bg-green-700 font-bold transition-all'
                                  >
                                    ✅ Save
                                  </button>
                                  <button
                                    onClick={() => {
                                      setEditingId(null)
                                      setNewStatus('')
                                    }}
                                    className='bg-gray-400 text-white text-xs px-3 py-1 rounded hover:bg-gray-500 font-bold transition-all'
                                  >
                                    ❌ Cancel
                                  </button>
                                </div>
                              ) : (
                                <button
                                  onClick={() => {
                                    setEditingId(t.id)
                                    setNewStatus(t.status)
                                  }}
                                  className='flex items-center gap-1 bg-blue-100 text-blue-700 text-xs px-3 py-1 rounded hover:bg-blue-200 font-bold transition-all'
                                >
                                  <FiEdit2 size={12} /> Edit
                                </button>
                              )}
                            </td>
                            <td className='px-6 py-4 text-xs text-gray-500'>
                              {new Date(t.createdAt).toLocaleDateString('en-PK')}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* USERS TAB */}
          {activeTab === 'users' && (
            <div className='bg-white rounded-lg border-2 border-gray-200 overflow-hidden shadow-lg'>
              {users.length === 0 ? (
                <div className='p-12 text-center text-gray-400'>
                  <p className='text-lg font-semibold'>No users found</p>
                </div>
              ) : (
                <div className='overflow-x-auto'>
                  <table className='w-full text-sm'>
                    <thead>
                      <tr className='bg-gradient-to-r from-gray-100 to-gray-50 border-b-2 border-gray-300'>
                        <th className='px-6 py-4 text-left font-bold text-gray-800'>ID</th>
                        <th className='px-6 py-4 text-left font-bold text-gray-800'>Name</th>
                        <th className='px-6 py-4 text-left font-bold text-gray-800'>Email</th>
                        <th className='px-6 py-4 text-left font-bold text-gray-800'>Role</th>
                        <th className='px-6 py-4 text-left font-bold text-gray-800'>Status</th>
                        <th className='px-6 py-4 text-left font-bold text-gray-800'>Joined</th>
                      </tr>
                    </thead>
                    <tbody className='divide-y'>
                      {users.map((u) => (
                        <tr key={u.id} className='hover:bg-green-50 transition-colors'>
                          <td className='px-6 py-4 font-bold text-green-600'>#{u.id}</td>
                          <td className='px-6 py-4 font-bold text-gray-800'>{u.name}</td>
                          <td className='px-6 py-4 text-gray-600'>{u.email}</td>
                          <td className='px-6 py-4'>
                            <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                              u.role === 'admin' ? 'bg-red-100 text-red-700' :
                              u.role === 'agent' ? 'bg-blue-100 text-blue-700' :
                              'bg-green-100 text-green-700'
                            }`}>
                              {u.role === 'admin' ? '🔐 Admin' : u.role === 'agent' ? '👨‍💼 Agent' : '👤 User'}
                            </span>
                          </td>
                          <td className='px-6 py-4'>
                            <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                              u.is_active ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-700'
                            }`}>
                              {u.is_active ? '✅ Active' : '⚫ Inactive'}
                            </span>
                          </td>
                          <td className='px-6 py-4 text-xs text-gray-500'>
                            {new Date(u.createdAt).toLocaleDateString('en-PK')}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default SuperPanel